# mbalHelloApp.R

library(rOpenserver)

# Initialize OpenServer
mbal_server <- OpenServer$new()

# Start Prosper
cmd = "MBAL.START"
mbal_server$DoCmd(cmd)

get_mbal_model <- function(model) {
    # function to get the model filename
    models_dir <- system.file("models", package = "rOpenserver")
    model_file <- file.path(models_dir, model)
    if (!file.exists(model_file)) stop("Model not found ...") else
        return(model_file)

}


# MBAL opens files a little bit different. The filename needs to be surrounded with
# double quote not single quotes as in Prosper or GAP.
model_file <- get_mbal_model(model = "oil.mbi")      # get the model filename
open_cmd <- 'MBAL.OPENFILE'                          # OpenServer command
open_cmd <- paste0(open_cmd, '("', model_file, '")') # compose the command
DoCmd(mbal_server, open_cmd)                         # open the model

# Enter the OOIP and write to MBAL.
ooip <- 300
DoSet(mbal_server, "MBAL.MB.TANK.OOIP", ooip)        # write value to MBAL

# run prediction
DoSlowCmd(mbal_server, "MBAL.MB.RUNPREDICTION")      # send command


oil_rate <- DoGet(mbal_server, "MBAL.MB.TRES[2][$][$].OILRATE")
oil_rate <- rDoGet(mbal_server, "MBAL.MB.TRES[2][0][$].OILRATE")

# extract the oil rate from first row of the table generated by the prediction.
DoGet(mbal_server, "MBAL.MB.TRES[2][0][0].OILRATE")  # retrieve value at matrix

# shutdown MBAL
Sys.sleep(3)                                         # wait 3 seconds
command = "MBAL.SHUTDOWN"
mbal_server$DoCmd(command)                           # send command
mbal_server <- NULL                                  # clean OpenServer process
